version: "3.8"
services:
  gantry_sim:
    build: .
    container_name: gantry_sim_container
    network_mode: host
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    command: /bin/bash
